name: bc_golden_plugin
description: Golden Plugin is a software that enables you to test the UI you develop against a reference image or a design in Figma.
repository: 'https://github.com/bancolombia/bc_golden_plugin'

version: 2.0.0-alpha.4

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  platform: ^3.1.0
  file: ^6.1.4
  provider: ^6.1.2
  equatable: ^2.0.5
  meta: ^1.9.1
  flutter_svg: ^2.0.0
  logger: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  dart_code_linter: ^1.0.0
  mockito: ^5.4.0
  build_runner: ^2.0.0
  image: ^4.5.4


flutter:

  uses-material-design: true


  assets:
    - assets/
  
  fonts:
    - family: CIBFontSans-Light
      fonts:
        - asset: assets/fonts/CIBFontSans-Light.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

